### PR TITLE
Add Permissions-Policy security header

### PR DESCRIPTION
**Pull request by Clemv95**
Adding  Permissions-Policy security header

### CODE REVIEW

**Comment by Zoey2936** [comment]
Hello, the problem with setting this header is that maybe some services being proxied need these permissions

**Comment by Clemv95** [comment]
> Hello, the problem with setting this header is that maybe some services being proxied need these permissions

Yeah that's why i put a large list

**Comment by Zoey2936** [comment]
yes, but if a backend server already has this header set, which limits access since features should be blocked for security we would override them

**Comment by Zoey2936** [comment]
also () means that this feauture is blocked, if you for example proxy peertube or invidious things like fullscreen will be blocked

**Comment by Clemv95** [comment]
Yeah i can understand
So maybe provide a field to choose what to allow and what to block ?

**Comment by Zoey2936** [comment]
that would be an option, but since this header is very individual per host, the users could also put it into the advanced config

**Comment by Clemv95** [comment]
> that would be an option, but since this header is very individual per host, the users could also put it into the advanced config

Yes that's true
But correct me if i'm wrong, when putting something in advanced config, it cancel the "simple" configuration of an host

**Comment by Clemv95** [comment]
> > that would be an option, but since this header is very individual per host, the users could also put it into the advanced config
> 
> Yes that's true But correct me if i'm wrong, when putting something in advanced config, it cancel the "simple" configuration of an host

Well just if adding a location *

**Comment by Zoey2936** [comment]
if you just add this
`more_set_headers "headernamer: headervalue";`
then the header will added and nothing else changed, other secure headers will be kept and location will also stay

**Comment by Zoey2936** [comment]
I know that this header is very good security, but since there is no universal good default, it is best if everyone configure it themselves if they need it

**Comment by Clemv95** [comment]
> I know that this header is very good security, but since there is no universal good default, it is best if everyone configure it themselves if they need it

Agree, thanks for your time !
That's a very nice project :)

**Pull request closed without merging**
