### PR TITLE
Regex Test

### PR DESCRIPTION
**Pull request by DavidCraftDev**

### CODE REVIEW

**Comment by DavidCraftDev** [comment]
@Zoey2936 Is everything still working? Changed the domain regex in the frontend

**Comment by Zoey2936** [comment]
no, the ci needs to be green

**Comment by Zoey2936** [comment]
@DavidCraftDev ping

**Comment by DavidCraftDev** [comment]
@Zoey2936 Pong

**Comment by DavidCraftDev** [comment]
@Zoey2936 I think I have solved the problem, but before you merge, can you please have a look on the regex I implemented to check if the domain names are correct? /^(?:\*\.)?(?:[^*().]+|\([^)]*\))*[^.]$/

**Comment by DavidCraftDev** [comment]
Bad, upstream merge

**Pull request closed without merging**
