### PR TITLE
Update nginx.js

### PR DESCRIPTION
**Pull request by theraw**
don't kill nginx that could return http errors when you make changes from panel

### CODE REVIEW

**Comment by Zoey2936** [comment]
I know killing it is not a good solution, but otherwise the memory leak of modsec will kill the entire server...

**Comment by Zoey2936** [comment]
There are 2 options:
- killing nginx until modsec fixes the memory leak
- removing modsec and reloading nginx

**Comment by Zoey2936** [comment]
no idea why ghcr returns 403...

**Comment by theraw** [comment]
:/ killing it is really bad idea you can test to apply changes theres some red bar when you click save cuz it gets killd and theres no response from api call

**Comment by Zoey2936** [comment]
I know... But I think, there are no other solutions, then I listed

**Comment by theraw** [comment]
well 🤷‍♂️ cancel pr?

**Comment by Zoey2936** [comment]
you can keep it open if you want, maybe I make nginx reload first after the response to the npm frontend...

**Comment by theraw** [comment]
i think is also a personal preference thing personally if i restart nginx my stats will reset so i cannot

**Comment by Zoey2936** [comment]
what do you mean? I'm a bit confused

**Comment by theraw** [comment]
things reset when you restart Nginx proxy_cache will reset
it doesn't only return error to npm api/dashboard, all sites are affected by it

**Pull request closed without merging**
